flowchart TD
    subgraph t1 ["Cedar/Thm/.../VerifyIsAuthorized.lean"]
        tauth[["verifyIsAuthorized_is_sound"]]:::darkGreen
    end
    subgraph t2 ["Cedar/Thm/WellTyped/Expr.lean"]
        teval[["well_typed_is_sound"]]:::darkGreen
    end
    subgraph s1 ["Cedar/Spec/Authorizer.lean"]
        auth(["isAuthorized"]):::white
    end
    subgraph s2 ["Cedar/Spec/Evaluator.lean"]
        eval(["evaluate"]):::white
    end
    tauth --> auth
    teval --> eval
    classDef white fill:#fff,color:#333,stroke:#999
    classDef darkGreen fill:#1B5E20,color:#fff
